name: bseb
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¹ For Hindi + English localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  dio: ^5.9.0
  flutter_spinkit: ^5.2.2
  sn_progress_dialog: ^1.2.0
  shared_preferences: ^2.5.3
  image_picker: ^1.2.1
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  flutter_downloader: ^1.12.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  marquee: ^2.3.0
  sms_autofill: ^2.3.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  image: ^4.5.4
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  cupertino_icons: ^1.0.8
  syncfusion_flutter_pdfviewer: ^31.2.16
  get: ^4.6.5   # For state management and easy localization
  google_sign_in: ^7.0.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  file_picker: ^10.3.7
  open_filex: ^4.4.0
  cached_network_image: ^3.4.1  # For image caching and better performance




flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true   # ðŸ”¹ Required for gen-l10n

  assets:
    - assets/images/splash.png
    - assets/images/splash.jpg
    - assets/images/app_logo.png
    - assets/images/bseb_bg.png
    - assets/images/bseb_new.png
    - assets/images/bseb_bg_new.png
    - assets/images/
    - assets/english.json
    - assets/hindi.json
    - assets/pdfs/9th.pdf
    - assets/pdfs/10th.pdf
    - assets/pdfs/11th.pdf
    - assets/pdfs/12th.pdf
    - assets/pdfs/others.pdf
    - assets/pdfs/pdf_icon.png
    - assets/pdfs/other_contacts.pdf
    - assets/pdfs/Marksheet_certification_correction.pdf
    - assets/pdfs/
